version: '3.9'

services:
  chat:
    build: ./chat_application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./chat_application/:/usr/src/chat_application/
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
