version: '3.9'

services:
  chat:
    build: ./chat_application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./chat_application/:/usr/src/chat_application/
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:6

  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chat_app
      - POSTGRES_PASSWORD=chat_app
      - POSTGRES_DB=chat_app_dev

volumes:
  postgres_data: