# Generated by Django 3.2.5 on 2021-07-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='slug',
            field=models.CharField(default='slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
